version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "90:80"
    depends_on:
      - gateway-service

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - task-service
      - user-service

  task-service:
    build:
      context: ./task-service
    ports:
      - "8080:8080"

  user-service:
    build:
      context: ./user-service
    ports:
      - "5000:5000"